/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PopulationVillagesRouteImport } from './routes/population.villages'
import { Route as PopulationMembersRouteImport } from './routes/population.members'
import { Route as PopulationFamiliesRouteImport } from './routes/population.families'
import { Route as PopulationVillagesVillageIdRouteImport } from './routes/population.villages.$villageId'
import { Route as PopulationMembersAddRouteImport } from './routes/population.members.add'
import { Route as PopulationFamiliesAddRouteImport } from './routes/population.families.add'
import { Route as PopulationFamiliesFamilyIdRouteImport } from './routes/population.families.$familyId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationVillagesRoute = PopulationVillagesRouteImport.update({
  id: '/population/villages',
  path: '/population/villages',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationMembersRoute = PopulationMembersRouteImport.update({
  id: '/population/members',
  path: '/population/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationFamiliesRoute = PopulationFamiliesRouteImport.update({
  id: '/population/families',
  path: '/population/families',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationVillagesVillageIdRoute =
  PopulationVillagesVillageIdRouteImport.update({
    id: '/$villageId',
    path: '/$villageId',
    getParentRoute: () => PopulationVillagesRoute,
  } as any)
const PopulationMembersAddRoute = PopulationMembersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => PopulationMembersRoute,
} as any)
const PopulationFamiliesAddRoute = PopulationFamiliesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => PopulationFamiliesRoute,
} as any)
const PopulationFamiliesFamilyIdRoute =
  PopulationFamiliesFamilyIdRouteImport.update({
    id: '/$familyId',
    path: '/$familyId',
    getParentRoute: () => PopulationFamiliesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/population/families': typeof PopulationFamiliesRouteWithChildren
  '/population/members': typeof PopulationMembersRouteWithChildren
  '/population/villages': typeof PopulationVillagesRouteWithChildren
  '/population/families/$familyId': typeof PopulationFamiliesFamilyIdRoute
  '/population/families/add': typeof PopulationFamiliesAddRoute
  '/population/members/add': typeof PopulationMembersAddRoute
  '/population/villages/$villageId': typeof PopulationVillagesVillageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/population/families': typeof PopulationFamiliesRouteWithChildren
  '/population/members': typeof PopulationMembersRouteWithChildren
  '/population/villages': typeof PopulationVillagesRouteWithChildren
  '/population/families/$familyId': typeof PopulationFamiliesFamilyIdRoute
  '/population/families/add': typeof PopulationFamiliesAddRoute
  '/population/members/add': typeof PopulationMembersAddRoute
  '/population/villages/$villageId': typeof PopulationVillagesVillageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/population/families': typeof PopulationFamiliesRouteWithChildren
  '/population/members': typeof PopulationMembersRouteWithChildren
  '/population/villages': typeof PopulationVillagesRouteWithChildren
  '/population/families/$familyId': typeof PopulationFamiliesFamilyIdRoute
  '/population/families/add': typeof PopulationFamiliesAddRoute
  '/population/members/add': typeof PopulationMembersAddRoute
  '/population/villages/$villageId': typeof PopulationVillagesVillageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/population/families'
    | '/population/members'
    | '/population/villages'
    | '/population/families/$familyId'
    | '/population/families/add'
    | '/population/members/add'
    | '/population/villages/$villageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/population/families'
    | '/population/members'
    | '/population/villages'
    | '/population/families/$familyId'
    | '/population/families/add'
    | '/population/members/add'
    | '/population/villages/$villageId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/population/families'
    | '/population/members'
    | '/population/villages'
    | '/population/families/$familyId'
    | '/population/families/add'
    | '/population/members/add'
    | '/population/villages/$villageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PopulationFamiliesRoute: typeof PopulationFamiliesRouteWithChildren
  PopulationMembersRoute: typeof PopulationMembersRouteWithChildren
  PopulationVillagesRoute: typeof PopulationVillagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/villages': {
      id: '/population/villages'
      path: '/population/villages'
      fullPath: '/population/villages'
      preLoaderRoute: typeof PopulationVillagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/members': {
      id: '/population/members'
      path: '/population/members'
      fullPath: '/population/members'
      preLoaderRoute: typeof PopulationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/families': {
      id: '/population/families'
      path: '/population/families'
      fullPath: '/population/families'
      preLoaderRoute: typeof PopulationFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/villages/$villageId': {
      id: '/population/villages/$villageId'
      path: '/$villageId'
      fullPath: '/population/villages/$villageId'
      preLoaderRoute: typeof PopulationVillagesVillageIdRouteImport
      parentRoute: typeof PopulationVillagesRoute
    }
    '/population/members/add': {
      id: '/population/members/add'
      path: '/add'
      fullPath: '/population/members/add'
      preLoaderRoute: typeof PopulationMembersAddRouteImport
      parentRoute: typeof PopulationMembersRoute
    }
    '/population/families/add': {
      id: '/population/families/add'
      path: '/add'
      fullPath: '/population/families/add'
      preLoaderRoute: typeof PopulationFamiliesAddRouteImport
      parentRoute: typeof PopulationFamiliesRoute
    }
    '/population/families/$familyId': {
      id: '/population/families/$familyId'
      path: '/$familyId'
      fullPath: '/population/families/$familyId'
      preLoaderRoute: typeof PopulationFamiliesFamilyIdRouteImport
      parentRoute: typeof PopulationFamiliesRoute
    }
  }
}

interface PopulationFamiliesRouteChildren {
  PopulationFamiliesFamilyIdRoute: typeof PopulationFamiliesFamilyIdRoute
  PopulationFamiliesAddRoute: typeof PopulationFamiliesAddRoute
}

const PopulationFamiliesRouteChildren: PopulationFamiliesRouteChildren = {
  PopulationFamiliesFamilyIdRoute: PopulationFamiliesFamilyIdRoute,
  PopulationFamiliesAddRoute: PopulationFamiliesAddRoute,
}

const PopulationFamiliesRouteWithChildren =
  PopulationFamiliesRoute._addFileChildren(PopulationFamiliesRouteChildren)

interface PopulationMembersRouteChildren {
  PopulationMembersAddRoute: typeof PopulationMembersAddRoute
}

const PopulationMembersRouteChildren: PopulationMembersRouteChildren = {
  PopulationMembersAddRoute: PopulationMembersAddRoute,
}

const PopulationMembersRouteWithChildren =
  PopulationMembersRoute._addFileChildren(PopulationMembersRouteChildren)

interface PopulationVillagesRouteChildren {
  PopulationVillagesVillageIdRoute: typeof PopulationVillagesVillageIdRoute
}

const PopulationVillagesRouteChildren: PopulationVillagesRouteChildren = {
  PopulationVillagesVillageIdRoute: PopulationVillagesVillageIdRoute,
}

const PopulationVillagesRouteWithChildren =
  PopulationVillagesRoute._addFileChildren(PopulationVillagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PopulationFamiliesRoute: PopulationFamiliesRouteWithChildren,
  PopulationMembersRoute: PopulationMembersRouteWithChildren,
  PopulationVillagesRoute: PopulationVillagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
