/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsReportTypeRouteImport } from './routes/reports_.$reportType'
import { Route as PopulationVillagesRouteImport } from './routes/population.villages'
import { Route as PopulationMembersRouteImport } from './routes/population.members'
import { Route as PopulationFamiliesRouteImport } from './routes/population.families'
import { Route as PopulationVillagesVillageIdRouteImport } from './routes/population.villages_.$villageId'
import { Route as PopulationMembersAddRouteImport } from './routes/population.members_.add'
import { Route as PopulationFamiliesAddRouteImport } from './routes/population.families_.add'
import { Route as PopulationFamiliesFamilyIdRouteImport } from './routes/population.families_.$familyId'
import { Route as PopulationMembersMemberIdEditRouteImport } from './routes/population.members_.$memberId.edit'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportTypeRoute = ReportsReportTypeRouteImport.update({
  id: '/reports_/$reportType',
  path: '/reports/$reportType',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationVillagesRoute = PopulationVillagesRouteImport.update({
  id: '/population/villages',
  path: '/population/villages',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationMembersRoute = PopulationMembersRouteImport.update({
  id: '/population/members',
  path: '/population/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationFamiliesRoute = PopulationFamiliesRouteImport.update({
  id: '/population/families',
  path: '/population/families',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationVillagesVillageIdRoute =
  PopulationVillagesVillageIdRouteImport.update({
    id: '/population/villages_/$villageId',
    path: '/population/villages/$villageId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PopulationMembersAddRoute = PopulationMembersAddRouteImport.update({
  id: '/population/members_/add',
  path: '/population/members/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationFamiliesAddRoute = PopulationFamiliesAddRouteImport.update({
  id: '/population/families_/add',
  path: '/population/families/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationFamiliesFamilyIdRoute =
  PopulationFamiliesFamilyIdRouteImport.update({
    id: '/population/families_/$familyId',
    path: '/population/families/$familyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PopulationMembersMemberIdEditRoute =
  PopulationMembersMemberIdEditRouteImport.update({
    id: '/population/members_/$memberId/edit',
    path: '/population/members/$memberId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/population/families': typeof PopulationFamiliesRoute
  '/population/members': typeof PopulationMembersRoute
  '/population/villages': typeof PopulationVillagesRoute
  '/reports/$reportType': typeof ReportsReportTypeRoute
  '/population/families/$familyId': typeof PopulationFamiliesFamilyIdRoute
  '/population/families/add': typeof PopulationFamiliesAddRoute
  '/population/members/add': typeof PopulationMembersAddRoute
  '/population/villages/$villageId': typeof PopulationVillagesVillageIdRoute
  '/population/members/$memberId/edit': typeof PopulationMembersMemberIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/population/families': typeof PopulationFamiliesRoute
  '/population/members': typeof PopulationMembersRoute
  '/population/villages': typeof PopulationVillagesRoute
  '/reports/$reportType': typeof ReportsReportTypeRoute
  '/population/families/$familyId': typeof PopulationFamiliesFamilyIdRoute
  '/population/families/add': typeof PopulationFamiliesAddRoute
  '/population/members/add': typeof PopulationMembersAddRoute
  '/population/villages/$villageId': typeof PopulationVillagesVillageIdRoute
  '/population/members/$memberId/edit': typeof PopulationMembersMemberIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/population/families': typeof PopulationFamiliesRoute
  '/population/members': typeof PopulationMembersRoute
  '/population/villages': typeof PopulationVillagesRoute
  '/reports_/$reportType': typeof ReportsReportTypeRoute
  '/population/families_/$familyId': typeof PopulationFamiliesFamilyIdRoute
  '/population/families_/add': typeof PopulationFamiliesAddRoute
  '/population/members_/add': typeof PopulationMembersAddRoute
  '/population/villages_/$villageId': typeof PopulationVillagesVillageIdRoute
  '/population/members_/$memberId/edit': typeof PopulationMembersMemberIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/population/families'
    | '/population/members'
    | '/population/villages'
    | '/reports/$reportType'
    | '/population/families/$familyId'
    | '/population/families/add'
    | '/population/members/add'
    | '/population/villages/$villageId'
    | '/population/members/$memberId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/population/families'
    | '/population/members'
    | '/population/villages'
    | '/reports/$reportType'
    | '/population/families/$familyId'
    | '/population/families/add'
    | '/population/members/add'
    | '/population/villages/$villageId'
    | '/population/members/$memberId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/reports'
    | '/population/families'
    | '/population/members'
    | '/population/villages'
    | '/reports_/$reportType'
    | '/population/families_/$familyId'
    | '/population/families_/add'
    | '/population/members_/add'
    | '/population/villages_/$villageId'
    | '/population/members_/$memberId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ReportsRoute: typeof ReportsRoute
  PopulationFamiliesRoute: typeof PopulationFamiliesRoute
  PopulationMembersRoute: typeof PopulationMembersRoute
  PopulationVillagesRoute: typeof PopulationVillagesRoute
  ReportsReportTypeRoute: typeof ReportsReportTypeRoute
  PopulationFamiliesFamilyIdRoute: typeof PopulationFamiliesFamilyIdRoute
  PopulationFamiliesAddRoute: typeof PopulationFamiliesAddRoute
  PopulationMembersAddRoute: typeof PopulationMembersAddRoute
  PopulationVillagesVillageIdRoute: typeof PopulationVillagesVillageIdRoute
  PopulationMembersMemberIdEditRoute: typeof PopulationMembersMemberIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports_/$reportType': {
      id: '/reports_/$reportType'
      path: '/reports/$reportType'
      fullPath: '/reports/$reportType'
      preLoaderRoute: typeof ReportsReportTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/villages': {
      id: '/population/villages'
      path: '/population/villages'
      fullPath: '/population/villages'
      preLoaderRoute: typeof PopulationVillagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/members': {
      id: '/population/members'
      path: '/population/members'
      fullPath: '/population/members'
      preLoaderRoute: typeof PopulationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/families': {
      id: '/population/families'
      path: '/population/families'
      fullPath: '/population/families'
      preLoaderRoute: typeof PopulationFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/villages_/$villageId': {
      id: '/population/villages_/$villageId'
      path: '/population/villages/$villageId'
      fullPath: '/population/villages/$villageId'
      preLoaderRoute: typeof PopulationVillagesVillageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/members_/add': {
      id: '/population/members_/add'
      path: '/population/members/add'
      fullPath: '/population/members/add'
      preLoaderRoute: typeof PopulationMembersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/families_/add': {
      id: '/population/families_/add'
      path: '/population/families/add'
      fullPath: '/population/families/add'
      preLoaderRoute: typeof PopulationFamiliesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/families_/$familyId': {
      id: '/population/families_/$familyId'
      path: '/population/families/$familyId'
      fullPath: '/population/families/$familyId'
      preLoaderRoute: typeof PopulationFamiliesFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/members_/$memberId/edit': {
      id: '/population/members_/$memberId/edit'
      path: '/population/members/$memberId/edit'
      fullPath: '/population/members/$memberId/edit'
      preLoaderRoute: typeof PopulationMembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ReportsRoute: ReportsRoute,
  PopulationFamiliesRoute: PopulationFamiliesRoute,
  PopulationMembersRoute: PopulationMembersRoute,
  PopulationVillagesRoute: PopulationVillagesRoute,
  ReportsReportTypeRoute: ReportsReportTypeRoute,
  PopulationFamiliesFamilyIdRoute: PopulationFamiliesFamilyIdRoute,
  PopulationFamiliesAddRoute: PopulationFamiliesAddRoute,
  PopulationMembersAddRoute: PopulationMembersAddRoute,
  PopulationVillagesVillageIdRoute: PopulationVillagesVillageIdRoute,
  PopulationMembersMemberIdEditRoute: PopulationMembersMemberIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
